version: '3'
services:
  database:
    image: 'bitnami/mariadb:10.6'
    #command: --default-authentication-plugin=mysql_native_password
    deploy:
      restart_policy:
        condition: on-failure
    volumes:
      - db_data:/bitnami/mariadb
    networks:
      - directus
    environment:
      MARIADB_CHARACTER_SET: utf8mb4
      MARIADB_COLLATE: utf8mb4_unicode_ci
      MARIADB_ROOT_PASSWORD: ${DATABASE_PASSWORD}
      MARIADB_DATABASE: directus
      MARIADB_USER: directus
      MARIADB_PASSWORD: ${DATABASE_PASSWORD}

  cache:
    image: redis:6
    networks:
      - directus
      - traefik-public

  directus:
    image: directus/directus:9
    volumes:
      - directus_extensions:/directus/extensions
    networks:
      - directus
      - traefik-public
    deploy:
      labels:
        - "traefik.docker.network=traefik-public"
        - "traefik.enable=true"
        - "traefik.constraint-label=traefik-public"
        - "traefik.http.routers.directus-http.rule=Host(`${PUBLIC_URL?Variable PUBLIC_URL not set}`)"
        - "traefik.http.routers.directus-http.entrypoints=http"
        - "traefik.http.routers.directus-http.middlewares=https-redirect"
        - "traefik.http.routers.directus-https.rule=Host(`${PUBLIC_URL?Variable PUBLIC_URL not set}`)"
        - "traefik.http.routers.directus-https.entrypoints=https"
        - "traefik.http.routers.directus-https.tls=true"
        - "traefik.http.routers.directus-https.tls.certresolver=le"
        - "traefik.http.services.directus.loadbalancer.server.port=8055"
    depends_on:
      - cache
      - database
    environment:
      KEY: ${KEY}
      SECRET: ${SECRET}

      DB_CLIENT: 'mysql'
      DB_HOST: 'database'
      DB_PORT: '3306'
      DB_DATABASE: 'directus'
      DB_USER: 'directus'
      DB_PASSWORD: ${DATABASE_PASSWORD}

      CACHE_ENABLED: 'true'
      CACHE_STORE: 'redis'
      CACHE_REDIS: 'redis://cache:6379'

      ADMIN_EMAIL: ${ADMIN_EMAIL}
      ADMIN_PASSWORD: ${ADMIN_PASSWORD}

      PUBLIC_URL: 'https://${PUBLIC_URL}'

      STORAGE_LOCATIONS: ${STORAGE_LOCATIONS}
      STORAGE_LKSE_DRIVER: ${STORAGE_LKSE_DRIVER}
      STORAGE_LKSE_KEY: ${STORAGE_LKSE_KEY}
      STORAGE_LKSE_SECRET: ${STORAGE_LKSE_SECRET}
      STORAGE_LKSE_BUCKET: ${STORAGE_LKSE_BUCKET}
      STORAGE_LKSE_REGION: ${STORAGE_LKSE_REGION}
      STORAGE_LKSE_ENDPOINT: ${STORAGE_LKSE_ENDPOINT}

networks:
  directus:
    external: false
  traefik-public:
    external: true

volumes:
  db_data:
    driver: local
  directus_extensions:
    driver: local